server:
  port: 7070
  shutdown: graceful
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudfsd
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
       
  
  

 
    # Optional h2 console port if not set or set 0, available port is given
      
    
    
  
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/ 
     
      
 
 
 
 