server:
  port: 0
  shutdown: graceful
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flightmanagement
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
       
  
  

 
    # Optional h2 console port if not set or set 0, available port is given
      
    
    
  
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/ 
     
      
 
 
 
 
